/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    ABreadcrumbItem: typeof import('antdv-next')['BreadcrumbItem']
    AButton: typeof import('antdv-next')['Button']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    AMenu: typeof import('antdv-next')['Menu']
  }
}

// For TSX support
declare global {
    const ABreadcrumb: (typeof import('antdv-next'))['Breadcrumb']
    const ABreadcrumbItem: (typeof import('antdv-next'))['BreadcrumbItem']
    const AButton: (typeof import('antdv-next'))['Button']
    const AConfigProvider: (typeof import('antdv-next'))['ConfigProvider']
    const AMenu: (typeof import('antdv-next'))['Menu']
}
